export const DEMO_MOVIES = [
  {
    imdbID: "tt1375666",
    Title: "Inception",
    Year: "2010",
    Poster: "/src/apps/pages-images/inception.jpg",
    Plot: "A thief who steals corporate secrets through dream-sharing technology is offered a chance at redemption.",
    imdbRating: "8.8",
    Genre: "Action, Sci-Fi",
  },
  {
    imdbID: "tt0816692",
    Title: "Interstellar",
    Year: "2014",
    Poster: "/src/apps/pages-images/Interstellar.jpg",
    Plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    imdbRating: "8.7",
    Genre: "Adventure, Drama, Sci-Fi",
  },
  {
    imdbID: "tt0468569",
    Title: "The Dark Knight",
    Year: "2008",
    Poster: "/src/apps/pages-images/dark_knight.jpg",
    Plot: "Batman raises the stakes in his war on crime with the help of Lt. Gordon and District Attorney Harvey Dent.",
    imdbRating: "9.0",
    Genre: "Action, Crime, Drama",
  },
  {
    imdbID: "tt4154796",
    Title: "Avengers: Endgame",
    Year: "2019",
    Poster: "/src/apps/pages-images/Avengers.jpg",
    Plot: "After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos's actions.",
    imdbRating: "8.4",
    Genre: "Action, Adventure, Drama",
  },
  {
    imdbID: "tt0111161",
    Title: "The Shawshank Redemption",
    Year: "1994",
    Poster: "/src/apps/pages-images/The Shawshank Redemption.jpg",
    Plot: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    imdbRating: "9.3",
    Genre: "Drama",
  },
  {
    imdbID: "tt0137523",
    Title: "Fight Club",
    Year: "1999",
    Poster: "/src/apps/pages-images/Fight Club.jpg",
    Plot: "An insomniac office worker and a devil-may-care soap maker form an underground fight club.",
    imdbRating: "8.8",
    Genre: "Drama",
  },
];
